name: Hello World!
run-name: Hello World! pipeline

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Time is
        run: |
          date
      - name: Directory contents are
        run: |
          ls
