name: Deployment pipeline
run-name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run eslint -- --fix

      - name: Unit tests
        run: npm run test

  playwright_tests:
    needs: simple_deployment_pipeline
    uses: ./.github/workflows/playwright.yml
    with:
      node-version: "20"

  deploy:
    runs-on: ubuntu-20.04
    needs: [simple_deployment_pipeline, playwright_tests]
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}